FC4E-CAT/fc4e-cat-api

README.md, api/pom.xml, api/src/main/java/org/grnet/cat/api/endpoints/UsersEndpoint.java, api/src/main/java/org/grnet/cat/api/filters/Registration.java, api/src/main/java/org/grnet/cat/api/filters/RegistrationFilter.java, api/src/main/java/org/grnet/cat/api/templates/OidcClientTemplate.java, api/src/main/java/org/grnet/cat/api/utils/Utility.java, api/src/main/resources/application.properties, api/src/main/resources/templates/client.html, api/src/test/java/org/grnet/cat/api/UsersEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/UserProfileDto.java, entity/src/main/java/org/grnet/cat/entities/Identified.java, entity/src/main/java/org/grnet/cat/entities/User.java, entity/src/main/java/org/grnet/cat/entities/UserProfile.java, entity/src/main/resources/application.properties, mapper/pom.xml, mapper/src/main/java/org/grnet/cat/mappers/UserMapper.java, pom.xml, repository/src/main/java/org/grnet/cat/repositories/UserRepository.java, service/src/main/java/org/grnet/cat/services/IdentifiedService.java, service/src/main/java/org/grnet/cat/services/UserService.java
This pull request introduces a new API endpoint that provides user profile information.
**Changes Made**
1. Created a new endpoint '/users/profile' to handle requests for user profile information.
2. Implemented the necessary backend logic to fetch user profile data from the database.
3. Designed the response structure to include essential details such as voperson_id, registration datetime.
4. Added appropriate error handling to ensure graceful handling of invalid requests or database failures.
5. Updated the API documentation to include information about the new endpoint and its usage.
=> [CAT-18] Add User Profile Information

api/src/main/java/org/grnet/cat/api/endpoints/IntegrationsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/UsersEndpoint.java, api/src/test/java/org/grnet/cat/api/IntegrationsEndpointTest.java, api/src/test/java/org/grnet/cat/api/UsersEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/SourceResponseDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/pagination/PageResource.java, entity/src/main/java/org/grnet/cat/enums/Source.java, mapper/src/main/java/org/grnet/cat/mappers/SourceMapper.java, repository/src/main/java/org/grnet/cat/repositories/UserRepository.java, service/src/main/java/org/grnet/cat/services/IntegrationService.java, service/src/main/java/org/grnet/cat/services/UserService.java
This PR adds a new resource /integrations to handle the intregration procedures that maybe needed to the CAT service. 
Also it adds a new endpoint GET /organisations to retrieve the integration sources from which the organisations can be retrieved
Integrations Sources are represented from Integration enumeration which keeps a record of {value,label,url} of the source.
example {"ror","ROR","https://api.ror.org/organizations"}.
=> CAT-33 [API] List of organisation integration sources

api/config/quarkus-realm.json, api/src/main/resources/application.properties
Make local development more convenient by pre-configuring local keycloak with all the needed options (extra clients and scopes) in order to have also the local ui play along automatically
⚠️ note: This PR is divided in 5 sub commits for making easier to review the changes step by step. After the review process it can be squashed into a single commit. Describing the changes step by step:
=> CAT-59 Update quarkus-realm in keycloak with have voperson_id and frontend-client

api/config/quarkus-realm.json, api/pom.xml, api/src/main/java/org/grnet/cat/api/endpoints/RolesEndpoint.java, api/src/main/resources/application.properties, api/src/test/java/org/grnet/cat/api/IntegrationsEndpointTest.java, api/src/test/java/org/grnet/cat/api/KeycloakTest.java, api/src/test/java/org/grnet/cat/api/UsersEndpointTest.java, api/src/test/java/org/grnet/cat/api/ValidationsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/RoleDto.java, entity/src/main/java/org/grnet/cat/entities/ListQuery.java, entity/src/main/java/org/grnet/cat/entities/Role.java, handler/src/main/java/org/grnet/cat/handlers/exception/AuthenticationExceptionHandler.java, handler/src/main/java/org/grnet/cat/handlers/exception/AuthorizationForbiddenExceptionHandler.java, handler/src/main/java/org/grnet/cat/handlers/exception/ClientErrorExceptionHandler.java, handler/src/main/java/org/grnet/cat/handlers/exception/ExceptionHandler.java, handler/src/main/java/org/grnet/cat/handlers/exception/ServerErrorExceptionHandler.java, handler/src/main/java/org/grnet/cat/handlers/exception/ValidationExceptionHandler.java, mapper/src/main/java/org/grnet/cat/mappers/RoleMapper.java, pom.xml, repository/pom.xml, repository/src/main/java/org/grnet/cat/repositories/KeycloakAdminRepository.java, repository/src/main/java/org/grnet/cat/repositories/RoleRepository.java, repository/src/main/resources/application.properties, service/pom.xml, service/src/main/java/org/grnet/cat/services/KeycloakAdminRoleService.java, service/src/main/java/org/grnet/cat/services/RoleService.java, service/src/main/java/org/grnet/cat/services/ValidationService.java
This Pull Request introduces the necessary changes to enable API communication with Keycloak. The goal is to automatically update the user role to "validated" upon admin validation approval.
- Integrated Keycloak Admin-CLI API
- Implemented the code to send the appropriate request to Keycloak, specifying the user's unique identifier and the new role.
=> [CAT-69] Implement API communication with Keycloak to change user role upon validation approval

CHANGELOG.md, api/config/quarkus-realm.json, api/src/main/java/org/grnet/cat/api/endpoints/TemplatesEndpoint.java, api/src/main/resources/application.properties, api/src/test/java/org/grnet/cat/api/TemplatesEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/TemplateDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/TemplateRequest.java, entity/src/main/java/org/grnet/cat/entities/Template.java, mapper/src/main/java/org/grnet/cat/mappers/TemplateMapper.java, repository/src/main/java/org/grnet/cat/repositories/TemplateRepository.java, service/src/main/java/org/grnet/cat/services/TemplateService.java
This Pull Request introduces a new API endpoint that allows admin users to create assessment templates. The new endpoint ensures that only admin users can access it, and it accepts a JSON object representing the assessment template, along with additional parameters like the actor and template type.
=> [CAT-113] Create Endpoint for Admin Users to Create Assessment Templates

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/CodelistEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AssessmentRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AssessmentResponseDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AssessmentTypeDto.java, entity/src/main/java/org/grnet/cat/entities/AssessmentType.java, mapper/src/main/java/org/grnet/cat/mappers/AssessmentTypeMapper.java, mapper/src/main/java/org/grnet/cat/mappers/ValidationMapper.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentTypeRepository.java, service/src/main/java/org/grnet/cat/services/AssessmentTypeService.java, service/src/main/java/org/grnet/cat/services/IntegrationService.java
This pull request addresses the JIRA ticket CAT-117, which aims to create a new API endpoint to retrieve the available assessment types. The implemented changes introduce a new endpoint and its associated functionality to serve the required data.
- Created a new API endpoint: GET /v1/codelist/assessment-types
- Implemented logic to fetch the available assessment types from the database.
=> [CAT-117] Create an endpoint that retrieves the available assessment types

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/IntegrationsEndpoint.java, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, api/src/test/java/org/grnet/cat/api/IntegrationsEndpointTest.java, entity/src/main/java/org/grnet/cat/entities/Validation.java, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, repository/src/main/java/org/grnet/cat/repositories/ActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentTypeRepository.java, repository/src/main/java/org/grnet/cat/repositories/Repository.java, repository/src/main/java/org/grnet/cat/repositories/TemplateRepository.java, repository/src/main/java/org/grnet/cat/repositories/UserRepository.java, repository/src/main/java/org/grnet/cat/repositories/ValidationRepository.java, service/src/main/java/org/grnet/cat/services/AssessmentService.java
This commit addresses the JIRA ticket CAT-91, which aims to create a new API endpoint to view list of assessments. The implemented changes introduce a new endpoint and its associated functionality to serve the required data.
=> [CAT-91] Create an API endpoint that allows to view list of assessments

CHANGELOG.md, api/config/quarkus-realm.json, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/TemplatesEndpoint.java, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, service/src/main/java/org/grnet/cat/services/assessment/AssessmentService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
We have generated a new endpoint that deletes an assessment if it is not published and belongs to the authenticated user.
=> [CAT-178] Delete private assessment

entity/src/main/resources/db/migration/V1.12__update_validation_status.sql, entity/src/main/resources/db/migration/V1.34__update_validation_status.sql
When running from scratch (first-time),
Hibernate is expecting an INTER: found [tinyint (Types#TINYINT)], but expecting [integer (Types#INTEGER)
So, either change SQL, or change Hibernate. I dont know which you prefer, I changed SQL.
=> use INTEGER insteadof TINYINT

data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/PartialJsonAssessmentResponse.java
We have changed this primitive type to wrapper class in order to avoid null values.
=> Change primitive type

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/SubjectsEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/JsonAssessmentRequest.java, service/src/main/java/org/grnet/cat/services/SubjectService.java, service/src/main/java/org/grnet/cat/services/assessment/AssessmentService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAbstractAssessmentService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
The API should provide flexibility for clients to either use an existing Subject by specifying its id in the subject.db_id property or create a new one by leaving subject.db_id empty and filling in the other three properties (subject.name, subject.type and subject.id).
Finally, the API should give precedence to the properties stored in the database. If a valid subject.db_id is provided, its associated Subject should be retrieved, and the values of name, type, and id in the Assessment should be overwritten with the corresponding values from the existing database Subject.
=> [CAT-276] Implement Flexible Logic for Saving Assessments in the Database

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/UserProfileDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/access/DenyAccess.java, entity/src/main/java/org/grnet/cat/entities/User.java, entity/src/main/java/org/grnet/cat/entities/history/AccessToCatService.java, entity/src/main/java/org/grnet/cat/entities/history/History.java, entity/src/main/resources/db/migration/tables/history/V1.51__history.sql, entity/src/main/resources/db/migration/tables/user/V1.52__banned.sql, repository/src/main/java/org/grnet/cat/repositories/HistoryRepository.java, service/src/main/java/org/grnet/cat/services/UserService.java
This Pull Request introduces a new API endpoint for adding the deny_access role to a user in Keycloak. The endpoint is designed to be used by administrators and serves the purpose of denying access to the API for the specified user.
=> [CAT-279] Deny access to the CAT Service

CHANGELOG.md, api/config/quarkus-realm.json, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, service/src/main/java/org/grnet/cat/services/UserService.java
During user registration, it is necessary to assign the identified role to the user by communicating with the Keycloak API. This process involves integrating with Keycloak to set the appropriate role for the newly registered user.
=> [CAT-295] Assign identified role to user during registration

CHANGELOG.md, pom.xml
- [#208](https://github.com/FC4E-CAT/fc4e-cat-api/pull/208) CAT-395 Public assessment not updated.
- [#209](https://github.com/FC4E-CAT/fc4e-cat-api/pull/209) CAT-398 Update PID Service Provider
=> Bumped version number to 1.5.1

entity/src/main/resources/db/migration/tables/json_schema/V1.65__update_json_schema_v5.sql, entity/src/main/resources/db/migration/templates/service/V1.64__update_service_template.sql
updated service provider template to include thresholds in tests. can compare between V1.64__update_service_template.sql and V1.58__update_service_template.sql to check the diffs. 
also added equals property in json schema to be permitted in assessment validation in order to support T24.1, T24.2 that succeeds when value=6 and value=7 correspondingly.
=> CAT-418 Fix Service Provider template to support thresholds in tests

CHANGELOG.md, pom.xml
- [#212](https://github.com/FC4E-CAT/fc4e-cat-api/pull/212) CAT-402 Duplicate test in assessment template.
- [#213](https://github.com/FC4E-CAT/fc4e-cat-api/pull/213) CAT-418 Fix Service Provider template to support thresholds in tests
- [#214](https://github.com/FC4E-CAT/fc4e-cat-api/pull/214) CAT-419 Flag thresholds as locked when having a required default value.
=> Bumped version number to 1.5.2 

CHANGELOG.md, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, entity/src/main/resources/db/migration/tables/json_schema/V1.80__update_json_schema_v7.sql
evidence_url definition in json schema for validation is changed to accept a format like this :
evidence_url: [ item1, item2 ]
where item is as: {"url":"htttps://google.com", "description":"description of url"} or {"url":"htttps://google.com"} 
meaning that description is optional.
=> CAT-450 Input type in the evidence

CHANGELOG.md, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/criterion/PrincipleCriterionResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Criterion.java, entity/src/main/java/org/grnet/cat/entities/registry/PrincipleCriterionJunction.java, mapper/src/main/java/org/grnet/cat/mappers/registry/CriterionActorMapper.java, mapper/src/main/java/org/grnet/cat/mappers/registry/PrincipleCriterionMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/PrincipleCriterionRepository.java, service/src/main/java/org/grnet/cat/services/registry/RegistryActorService.java
added id to responses to get the criterion id
return the principlecriterionjunctionresponse in the get /motivations/{id}/actors/{id}/criteria
fixed some issues with pagination and sorting
=> CAT-516 Criteria items under motivation are represented with a bit different schema under two different GET calls - Missing criterion id

CHANGELOG.md, entity/src/main/java/org/grnet/cat/entities/registry/CriterionActorId.java, entity/src/main/java/org/grnet/cat/entities/registry/CriterionActorJunction.java, entity/src/main/resources/db/migration/tables/registry/V1.135__exists_foreign_key_stored_procedure.sql, entity/src/main/resources/db/migration/tables/registry/V1.136__exists_primary_key_stored_procedure.sql, entity/src/main/resources/db/migration/tables/registry/V1.137__update_criterion_actor.sql
changes to scripts to set motivation_id as part of primary key of p_Criterion_Actor.
NULL values in motivation_lodMTV are updated to keep the EOSC PID Policy id.
also scripts to update the primary key 
and changes in implementation to support this.
=> CAT-590 Fix CriterionActorJunction key to keep Motivation id

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java
Added GET /registry/motivations/{id}/actors/{actor-id}/template without constraints on publish/unpublished status of Motivation in order to preview motivation's json unrestrictedly
=> CAT-607 Template's view issue when unpublished motivation , during preview motivation

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/MetricDefinitionExtendedResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/MetricDefinitionRequest.java, mapper/src/main/java/org/grnet/cat/mappers/registry/MetricDefinitionMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/MetricDefinitionRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
> {
>   "size_of_page": 1,
>   "number_of_page": 1,
>   "total_elements": 1,
>   "total_pages": 1,
>   "content": [
>     {
>       "metric_id": "pid_graph:6805DC1D",
>       "metric_label": "Performance Metric",
>       "metric_description": "This metric measures performance.",
>       "type_algorithm_id": "pid_graph:2050775C",
>       "type_algorithm_label": "Weighted Sum",
>       "type_metric_id": "pid_graph:35966E2B",
>       "type_metric_label": "Open Review",
>       "type_benchmark_id": "pid_graph:0917EC0D",
>       "type_benchmark_label": "Integer-Binary-AND",
>       "type_benchmark_description": "The benchmark maps the aggregate of a number of binary tests, expressed as an integer, to a binary assessment and all tests must pass. The benchmark equals the number of tests.",
> …
=> CAT-695: Implement GET and PUT /metric - definition by Motivation API Endpoint

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, api/src/test/java/org/grnet/cat/api/KeycloakTest.java, api/src/test/java/org/grnet/cat/api/registry/MotivationEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/motivation/DeletePrincipleCriterionRequest.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationPrincipleRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/PrincipleCriterionRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/PrincipleRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
Delete a principle inside a motivation: this will remove the principle-motivation relation as well as the principle-criterion-motivation relation. principle will be deleted from registry only in the case the principle has no relations principle-motivation, principle-criterion-motivation with any other motivation except the one trying to update
Update a principle inside a motivation : this will update the principle fileds. only in the case there does not exist any other relations principle-motivation, principle-criterion-motivation with any other motivation except the one trying to update
=> CAT-653 Delete & Update Principle in a motivation

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/TestDefinitionEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/TestEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/TestEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/test/TestAndTestDefinitionRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/test/TestAndTestDefinitionResponse.java, mapper/src/main/java/org/grnet/cat/mappers/registry/TestDefinitionMapper.java, mapper/src/main/java/org/grnet/cat/mappers/registry/TestMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/TestDefinitionRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/TestRepository.java, service/src/main/java/org/grnet/cat/services/registry/TestDefinitionService.java, service/src/main/java/org/grnet/cat/services/registry/TestService.java
```
{
"test": {
"tes": "adsasdasdasd",
"label": "PID Persistence - Service - Evidence",
"description": "Evidence is provided by the service that PIDs cannot be deleted."
},
"test_definition": {
"test_method_id": "pid_graph:B733A7D5",
"label": "Manual confirmation of user authentication required for access to sensitive metadata.",
"param_type": "onscreen",
"test_params": "userAuth\"|\"evidence",
"test_question": "\"Does access to Sensitive PID Kernel Metadata require user authentication?\"|\"Provide evidence of this provision via a link to a specification, user guide, or API definition.\"",
"tool_tip": "\"Users need to be authenticated and requisite permissions must apply for access to sensitive metadata\"|\"A document, web page, or publication describing provisions\""
}
}
```
```
{ …
```
=> CAT-697: Update /registry/tests Endpoints to Include All test and test-definition Fields

CHANGELOG.md, entity/src/main/java/org/grnet/cat/entities/registry/RegistryTemplate.java, entity/src/main/resources/db/migration/tables/registry/V1.52__update_registry_template.sql, repository/src/main/java/org/grnet/cat/repositories/registry/RegistryTemplateRepository.java
Seemed that the registry_template view needed to add motivation id for metrics, metric tests and criterion metrics relations to be retrieved the entities only for the one motivation
=> CAT-741 Motivation preview displays wrong json when add/remove elements in motivation

CHANGELOG.md, entity/src/main/resources/db/migration/tables/registry/V1.55__update_metric_benchmark.sql
change db p_Metric_Definition for C7 criterion -metric , to have value benchmark=1
=> CAT-745 C7 criterion fails due to wrong benchmark value

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java
Admin not permitted to publish assessment, not owned by himself. it is fixed now
=> CAT-749 API call: admin publish assessment gets 403 when admin

CHANGELOG.md, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
1) When get public assessment without loggin to CAT , the user does not have a voperson_id. as the assessment to be returned contained sharedByUser, sharedToUser a check to the voperson_id was done and this returned null. we fixed this and  also added a test , that we were missing
2) At some point for some reason, we missed filling the assessment's id inside the assessment_doc. fixed this
=> CAT-783  CAT-791 API- GET Public Assessment 400 error/Assessment's id inside assessment_doc is null

CHANGELOG.md, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/MetricDefinitionExtendedResponse.java, repository/src/main/java/org/grnet/cat/repositories/registry/MetricDefinitionRepository.java, service/src/main/java/org/grnet/cat/services/registry/metric/MetricService.java
**Response:**
```{
"metric_id": "pid_graph:0A42DC0E",
"metric_mtr": "M11",
"metric_label": "Versioning Procedure",
"metric_description": "Evidence is available that a clear versioning procedure or policy exists and is available",
"type_algorithm_id": "pid_graph:7A976659",
"type_algorithm_label": "Test = Metric",
"type_metric_id": "pid_graph:8D79984F",
"type_metric_label": "Binary",
"type_benchmark_id": "pid_graph:7085006F",
"type_benchmark_label": "Binary-Binary",
"type_benchmark_description": "The benchmark maps a binary metric value to binary assessment outcome (Pass/ Fail). The inverse can also be done.",
"type_benchmark_patter": "M[0,1] → [Fail, Pass]",
"motivation_id": "pid_graph:34A9189F",
"value_benchmark": "1",
"used_by_motivations": [
{
"id": "pid_graph:34A9189F",
"mtv": …
```
=> CAT-792: Retrieve Associated Motivations for Metrics

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MetricEndpoint.java, repository/src/main/java/org/grnet/cat/repositories/registry/MetricDefinitionRepository.java, service/src/main/java/org/grnet/cat/services/registry/metric/MetricService.java
Updated sorting options to lastTouch, **metric.MTR**, and valueBenchmark (need to check with UI before merging).
=> CAT-788: Wrong sort values for /registry/metrics

entity/src/main/resources/db/migration/tables/registry/V1.58__modify_testQuestion_column_size.sql, entity/src/main/resources/db/migration/tables/registry/V1.59__recreate_registry_template.sql
- Updated the `testQuestion` column to VARCHAR(500). 
- Dropped and recreated the `registry_templates` view due to dependency changes caused by the modification of the `testQuestion` column size from VARCHAR(255) to VARCHAR(500) in the `p_Test_Definition` table.
=> CAT-805: Update testQuestion field to VARCHAR(500) TestDefinition table

CHANGELOG.md, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
published element in json was not updated correctly when publish/unpublish from admin
=> CAT-749 API call: admin publish assessment gets 403 when admin -version 2

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsV2Endpoint.java, api/src/main/resources/application.properties, api/src/main/resources/templates/zenodo_completed_publish_process_notification.html, api/src/main/resources/templates/zenodo_draft_deposit_notification.html, api/src/main/resources/templates/zenodo_failed_publish_deposit_notification.html, api/src/main/resources/templates/zenodo_failed_publish_process_notification.html, api/src/main/resources/templates/zenodo_publish_assessment_notification.html, api/src/main/resources/templates/zenodo_publish_deposit_notification.html, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/ZenodoAssessmentInfoResponse.java, entity/src/main/java/org/grnet/cat/entities/ZenodoAssessmentInfo.java, entity/src/main/java/org/grnet/cat/entities/ZenodoAssessmentInfoId.java, entity/src/main/resources/db/migration/tables/assessment/V1.60__add_zenodo_assessment_info.sql, enum/src/main/java/org/grnet/cat/enums/MailType.java, enum/src/main/java/org/grnet/cat/enums/ZenodoState.java, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, mapper/src/main/java/org/grnet/cat/mappers/ZenodoAssessmentInfoMapper.java, pom.xml, repository/src/main/java/org/grnet/cat/repositories/ZenodoAssessmentInfoRepository.java, service/pom.xml, service/src/main/java/org/grnet/cat/services/MailerService.java, service/src/main/java/org/grnet/cat/services/zenodo/ZenodoClient.java, service/src/main/java/org/grnet/cat/services/zenodo/ZenodoService.java, validator/src/main/java/org/grnet/cat/constraints/ValidZenodoAction.java, validator/src/main/java/org/grnet/cat/validators/ValidZenodoActionValidator.java
Only published assessments in cat can be published
Only assessment creator or shared user can publish assessment
file should be pdf, in endpoint as binary, byte[]
We have the following statuses to define the steps in publish zenodo
PROCESS_INIT
DEPOSIT_CREATED
FILE_UPLOADED_TO_DEPOSIT
DEPOSIT_PUBLISHED
PROCESS_COMPLETED
PROCESS_FAILED
After each step is completed successfully , the state changes
Steps:     PROCESS_INIT  1. Create deposit to zenodo
                 DEPOSIT_CREATED   2. convert binary to pdf file and upload to deposit
                FILE_UPLOADED_TO_DEPOSIT  3. store in database in ZenodoAssessmentInfo table the information.
                 FILE_UPLOADED_TO_DEPOSIT  4. publish deposit
               DEPOSIT_PUBLISHED   5. update database ZenodoAssessmentInfo
              …
=> CAT-827 CAT-829 CAT-828 Publish Assessment in Zenodo / Store zenodo info in database/ Notifications to creator

CHANGELOG.md, api/config/quarkus-realm.json
Fix keycloak > frontend client > web origins entry for 127.0.0.1:3000
=> CAT-856 Fix keycloak CORS policy towards 127.0.0.1
