api/src/main/java/org/grnet/cat/api/endpoints/UsersEndpoint.java, api/src/main/resources/application.properties, api/src/test/java/org/grnet/cat/api/UsersEndpointTest.java, data-transfer-object/pom.xml, data-transfer-object/src/main/java/org/grnet/cat/dtos/UpdateUserProfileDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/UserProfileDto.java, entity/src/main/java/org/grnet/cat/entities/User.java, entity/src/main/java/org/grnet/cat/entities/UserProfile.java, entity/src/main/resources/db/migration/V1.1__update_user.sql, repository/src/main/java/org/grnet/cat/repositories/UserRepository.java, service/src/main/java/org/grnet/cat/services/UserService.java
This pull request introduces a new endpoint that allows users to update their profile metadata. It enhances the user experience by providing a way to modify and manage additional information associated with their profile.
=> [CAT-28] Update User Profile Metadata Endpoint

README.md, api/pom.xml, api/src/main/java/org/grnet/cat/api/endpoints/IntegrationsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/UsersEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/ValidationsEndpoint.java, api/src/main/resources/application.properties, api/src/test/java/org/grnet/cat/api/IntegrationsEndpointTest.java, api/src/test/java/org/grnet/cat/api/KeycloakTest.java, api/src/test/java/org/grnet/cat/api/UsersEndpointTest.java, api/src/test/java/org/grnet/cat/api/ValidationsEndpointTest.java, data-transfer-object/pom.xml, data-transfer-object/src/main/java/org/grnet/cat/dtos/PromotionRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/SourceResponseDto.java, entity/pom.xml, entity/src/main/java/org/grnet/cat/entities/Validation.java, entity/src/main/resources/db/migration/V1.2__validation.sql, enum/pom.xml, enum/src/main/java/org/grnet/cat/enums/Source.java, enum/src/main/java/org/grnet/cat/enums/ValidationStatus.java, pom.xml, repository/src/main/java/org/grnet/cat/repositories/ValidationRepository.java, service/src/main/java/org/grnet/cat/services/IdentifiedService.java, service/src/main/java/org/grnet/cat/services/ValidationService.java, validator/pom.xml, validator/src/main/java/org/grnet/cat/constraints/StringEnumeration.java, validator/src/main/java/org/grnet/cat/validators/StringEnumerationValidator.java
This Pull Request adds a new User Validation endpoint to the API, allowing identified users to request promotion to become validated users.
- Added a new endpoint `/v1/validations` to handle user promotion requests.
- Implemented the necessary service and repository methods for user promotion.
- Updated the swagger documentation to include the new endpoint.
=> [CAT-27] User Validation Endpoint

.gitignore, api/src/main/java/org/grnet/cat/api/endpoints/IntegrationsEndpoint.java, api/src/test/java/org/grnet/cat/api/IntegrationsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/pagination/PageResource.java, entity/src/main/java/org/grnet/cat/entities/ListQuery.java, enum/src/main/java/org/grnet/cat/enums/Source.java, mapper/src/main/java/org/grnet/cat/mappers/OrganisationMapper.java, service/src/main/java/org/grnet/cat/services/IntegrationService.java
This pr includes endpoint GET /organisations/ROR?name=value&page=pageVal to retrieve organisations by name for ROR.
ROR search retrieves 20 elements per page so the size of pagination in the request is defined to be 20.
=> search organisations in ror by name

api/src/main/resources/application.properties
This pr changes Keycloack dev port in application.properties to 58080
=> change dev keycloak to 58080

data-transfer-object/src/main/java/org/grnet/cat/dtos/ValidationResponse.java, mapper/src/main/java/org/grnet/cat/mappers/ValidationMapper.java
On validations responses also include:
-   user name
-   user surname
-   user email
-  actor name
=> [CAT-77] Add extended user and actor info on validation response

data-transfer-object/pom.xml, data-transfer-object/src/main/java/org/grnet/cat/dtos/TemplateDto.java, mapper/pom.xml, mapper/src/main/java/org/grnet/cat/mappers/TemplateMapper.java, pom.xml
fix to return template doc to json object and not string as it is now
=> CAT fix: template doc from string to json object

api/config/quarkus-realm.json, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, api/src/test/java/org/grnet/cat/api/KeycloakTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AssessmentRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AssessmentResponseDto.java, entity/src/main/java/org/grnet/cat/entities/Assessment.java, entity/src/main/resources/db/migration/V1.10__assessment.sql, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/src/main/java/org/grnet/cat/services/AssessmentService.java
This pr includes all the implementation needed to create an assessment for a validation request.
=> CAT-88 Create API endpoint to allow user to store a new assessment (CREATE)

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/UpdateAssessmentRequest.java, entity/src/main/resources/db/migration/V1.11__update_template_doc.sql, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/src/main/java/org/grnet/cat/services/AssessmentService.java
This pr includes implementation to update the assessment's json document
Also includes an .sql script to update the template json document inserted to the db, to fix a minor typo in template's json
=> CAT-90 Create API endpoint to allow user to update an existing assessment (PUT)

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/OrganisationResponseDto.java, entity/src/main/java/org/grnet/cat/entities/Organisation.java, enum/src/main/java/org/grnet/cat/enums/Source.java, service/src/main/java/org/grnet/cat/services/AssessmentService.java, service/src/main/java/org/grnet/cat/services/IntegrationService.java
This pr adds implementantation to search ror organisations also by acronym. it adds acronym field  to the response with value the acronym field for ror, or abbreviation for eosc.
=> CAT-75 Investigate to enrich ROR search organisation on acronym

CHANGELOG.md, api/config/quarkus-realm.json, api/src/main/java/org/grnet/cat/api/endpoints/TemplatesEndpoint.java, api/src/main/resources/application.properties, api/src/test/java/org/grnet/cat/api/TemplatesEndpointTest.java, enum/src/main/java/org/grnet/cat/enums/Source.java, repository/src/main/java/org/grnet/cat/repositories/TemplateRepository.java, service/src/main/java/org/grnet/cat/services/TemplateService.java
This pr implements an endpoint to fetch list of templates providing the actor id
=> CAT-111 Create API endpoint to get the list of templates for an actor

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AdminValidationsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/ValidationsEndpoint.java, api/src/main/java/org/grnet/cat/api/utils/Utility.java, entity/src/main/java/org/grnet/cat/converter/StatusAttributeConverter.java, entity/src/main/java/org/grnet/cat/entities/Validation.java, entity/src/main/resources/db/migration/V1.12__update_validation_status.sql, enum/src/main/java/org/grnet/cat/enums/ValidationStatus.java, repository/src/main/java/org/grnet/cat/repositories/ValidationRepository.java, service/src/main/java/org/grnet/cat/services/ValidationService.java
We have modified the existing "Validation" table in the database to enhance the efficiency of table ordering.
=> [CAT-122] Update "status" column data type in the Validation table

entity/src/main/resources/db/migration/V1.13__update_template_doc_v2.sql, enum/src/main/java/org/grnet/cat/enums/Source.java
this pr contains an update script for sql to update the template doc to version 2 as reported in the CAT-124 jira task
=> CAT-124 Update assessment JSON schema with ids and additional fields

CHANGELOG.md, entity/src/main/resources/db/migration/V1.16__update_template_doc_v5.sql
This PR updates template json to version 5 by changing imperative value to "should" instead of "may"
=> CAT-156 Add imperative = should in owner.template

CHANGELOG.md, entity/src/main/resources/db/migration/V1.17__update_template_doc_v6.sql
This PR includes update to template json , by changes values of values/results with null
=> CAT-157 Support non-filled values for values/results in tests and metrics of template

CHANGELOG.md, entity/src/main/resources/db/migration/V1.19__update_template_doc_v8.sql
This PR includes a small update on template json for PID OWNER , by adding result filed in test element
=> CAT-163 Small update in PID owner template - add an extra field

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/ValidationResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/JsonAssessmentRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/PartialJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/template/TemplateOrganisationDto.java, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, service/src/main/java/org/grnet/cat/services/assessment/AssessmentService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
When getting the assessment list, we return the most important fields that identify each assessment.
=> [CAT-160] Partial Assessment Information

entity/src/main/resources/db/development/V1.6.2__pre_register_users.sql
This script inserts users into database even if an error occurs.
=> Fix pre-register user script

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AssessmentDoc.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AssessmentResponse.java, entity/src/main/java/org/grnet/cat/entities/Assessment.java, entity/src/main/resources/db/migration/V1.21__change_assessment_id.sql, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/src/main/java/org/grnet/cat/services/assessment/AssessmentService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
Reverts FC4E-CAT/fc4e-cat-api#73
=> Revert "[CAT-159] Change assessment id from bigint to uuid"

entity/src/main/resources/db/migration/V1.22__insert_actor.sql
In order to create template for Actor Scheme, we need to add to Actor sql table the specific actor. This PR adds an sql script that inserts into the table the new entry.
=> CAT-169 Create template for actor: Scheme 

entity/src/main/resources/db/migration/V1.24__create_manager_template.sql
This PR adds an sql script to insert a new template in Template table for actor Manager
=> CAT-167 Create template for actor: Manager

CHANGELOG.md, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/InformativeResponse.java, entity/src/main/java/org/grnet/cat/entities/Template.java, entity/src/main/resources/db/migration/V1.25__add_colum_json_schema_to_template.sql, entity/src/main/resources/db/migration/V1.26__add_actor_json_schema.sql, exception/src/main/java/org/grnet/cat/exceptions/BadRequestException.java, exception/src/main/java/org/grnet/cat/exceptions/CustomValidationException.java, handler/src/main/java/org/grnet/cat/handlers/exception/BadRequestExceptionHandler.java, pom.xml, service/pom.xml, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
Each new assessment for the PID Owner is validated against its corresponding JSON schema.
=> [CAT-183] Generate JSON Schema for PID Owner Template

entity/src/main/resources/db/migration/V1.27__update_scheme_template.sql
in this pr we update template of scheme actor, to fix a bug
=> fix json of scheme template

CHANGELOG.md, api/src/test/java/org/grnet/cat/api/TemplatesEndpointTest.java, entity/src/main/resources/db/migration/V1.28__create_service_template.sql, entity/src/main/resources/db/migration/V1.29__update_authority_template.sql, entity/src/main/resources/db/migration/V1.30__update_scheme_template_v2.sql, entity/src/main/resources/db/migration/V1.31__update_manager_template.sql
this pr adds a sql script to add a new entry in Template sql table, for service Template
=> CAT-168 Create template for actor: Service

entity/src/main/resources/db/migration/V1.12__update_validation_status.sql, entity/src/main/resources/db/migration/V1.34__update_validation_status.sql
Reverts FC4E-CAT/fc4e-cat-api#85
=> Revert "use INTEGER insteadof TINYINT"

entity/src/main/resources/db/migration/V1.34__update_scheme_template_v3.sql
this pr includes a fix at the pid scheme template json
=> update pid scheme template

CHANGELOG.md, api/config/quarkus-realm.json, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/main/resources/application.properties, data-transfer-object/src/main/java/org/grnet/cat/dtos/template/TemplateSubjectDto.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
We have created a new endpoint returning the list of objects already created / used by a specific actor by a specific user.
=> List of Objects

api/src/main/java/org/grnet/cat/api/endpoints/UsersEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/template/TemplateSubjectDto.java, pom.xml, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/pom.xml, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
A list of objects should not contain duplicate objects.
=> Return unique objects

entity/src/main/resources/db/migration/V1.35__update_scheme_template_v4.sql, entity/src/main/resources/db/migration/V1.36__update_authority_template_v2.sql, entity/src/main/resources/db/migration/V1.37__update_owner_template_v9.sql, entity/src/main/resources/db/migration/V1.38__update_manager_template_v2.sql, entity/src/main/resources/db/migration/V1.39__update_service_template_v2.sql
This pr contains update sql  scripts for the templates based on the feedback Natascha provided, as described in the jira task
=> CAT-214 Fixes on templates based on feedback from Natascha

api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
We have created a new endpoint returning the list of objects already created / used by a specific user.
=> List of objects by a specific user

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/SubjectsEndpoint.java, api/src/test/java/org/grnet/cat/api/SubjectsEndpointTest.java, service/src/main/java/org/grnet/cat/services/SubjectService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAbstractAssessmentService.java
We have introduced a new API endpoint which is responsible for deleting a new Subject.
=> [CAT-263] Delete a subject

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/SubjectsEndpoint.java, entity/src/main/java/org/grnet/cat/entities/Subject.java, entity/src/main/resources/db/migration/V1.43__new_column_subject.sql, mapper/src/main/java/org/grnet/cat/mappers/SubjectMapper.java, repository/src/main/java/org/grnet/cat/repositories/SubjectRepository.java, service/src/main/java/org/grnet/cat/services/SubjectService.java
We have introduced a new API endpoint which is responsible for retrieving the created Subjects.
=> [CAT-274] Fetch the created Subjects

api/src/main/java/org/grnet/cat/api/endpoints/SubjectsEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/subject/UpdateSubjectRequestDto.java, mapper/src/main/java/org/grnet/cat/mappers/SubjectMapper.java, service/src/main/java/org/grnet/cat/services/SubjectService.java
We have introduced a new API endpoint which is responsible for updating an existing Subject.
=> [CAT-262] Update a Subject

api/src/main/java/org/grnet/cat/api/endpoints/SubjectsEndpoint.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/src/main/java/org/grnet/cat/services/SubjectService.java
returns a list of assessments for a specific object specified by its id
implements an endpoint at 
/v1/subjects
GET /{id}/assessments
=> CAT-273 [API] - List of assessments per object

api/config/quarkus-realm.json, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/statistics/AssessmentPerActorDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/statistics/AssessmentStatisticsResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/statistics/StatisticsResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/statistics/SubjectStatisticsResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/statistics/UserStatisticsResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/statistics/ValidationStatisticsResponse.java, entity/src/main/java/org/grnet/cat/entities/AssessmentPerActor.java, enum/src/main/java/org/grnet/cat/enums/UserType.java, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRoleStatistics.java, repository/src/main/java/org/grnet/cat/repositories/KeycloakAdminRepository.java, repository/src/main/java/org/grnet/cat/repositories/RoleRepository.java, repository/src/main/java/org/grnet/cat/repositories/UserRepository.java, repository/src/main/java/org/grnet/cat/repositories/ValidationRepository.java, service/src/main/java/org/grnet/cat/services/KeycloakAdminRoleService.java, service/src/main/java/org/grnet/cat/services/StatisticsEnum.java, service/src/main/java/org/grnet/cat/services/SubjectService.java, service/src/main/java/org/grnet/cat/services/UserService.java, service/src/main/java/org/grnet/cat/services/ValidationService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
Statistics for admin about Assessments, Validations , Users,Objects.
/admin/statistic
* In validations as pending is considered the validations with PENDING or REVIEW status
=> CAT-289 As an admin i want to see some statistics in CAT

api/config/quarkus-realm.json, entity/src/main/resources/db/development/V1.6.3__pre_register_users_v2.sql
We created admin_ui [admin,identified] ,identified_ui[identified] users.
=> Create dedicated users for UI testing in CAT-API/keycloak

api/src/main/resources/application.properties, api/src/test/java/org/grnet/cat/api/ValidationsEndpointTest.java, entity/src/main/resources/db/development/V1.6.3__pre_register_users_v2.sql, service/src/main/java/org/grnet/cat/services/UserService.java
under api/applications.properties a new param --auto.approve.validations is introduced to define if the validations will be auto approved or not. 
By default auto.approve.validations=false
=> CAT-299 Mode for CAT-API to automatically approve new validation requests

api/src/main/resources/application.properties, api/src/test/java/org/grnet/cat/api/ValidationsEndpointTest.java, service/src/main/java/org/grnet/cat/services/UserService.java
rename param from auto.approve.validations to cat.validations.approve.auto
=> rename auto approve validations config param

CHANGELOG.md, pom.xml
=> Bumped api version to 1.2.2

CHANGELOG.md, pom.xml, service/src/main/java/org/grnet/cat/services/UserService.java
**Added**
- Fill in Validation with User Details.
=> Version 1.2.3

CHANGELOG.md, pom.xml
- CAT-320 Implement Custom Organization Source Feature.
=> Bumped api version to 1.2.4

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/IntegrationsEndpoint.java, api/src/test/java/org/grnet/cat/api/IntegrationsEndpointTest.java, api/src/test/java/org/grnet/cat/api/ValidationsEndpointTest.java, enum/src/main/java/org/grnet/cat/enums/Source.java, pom.xml, service/src/main/java/org/grnet/cat/services/IntegrationService.java, service/src/main/java/org/grnet/cat/services/UserService.java
- CAT-320 Implement Custom Organization Source Feature.
=> Version 1.2.4 

CHANGELOG.md, pom.xml
- Update Manager template to include best practices in guidelines
=> Bumped api version to 1.2.5

service/src/main/java/org/grnet/cat/services/MailerService.java
Reverts FC4E-CAT/fc4e-cat-api#150
=> Revert "change completable future"

service/src/main/java/org/grnet/cat/services/UserService.java
Reverts FC4E-CAT/fc4e-cat-api#154
=> Revert "mailer sending mails out of thread"

api/pom.xml, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/ValidationsEndpoint.java, api/src/main/resources/templates/user_created_validation.html, api/src/main/resources/templates/validation_status_updated.html, enum/pom.xml, enum/src/main/java/org/grnet/cat/enums/MailType.java, pom.xml, service/src/main/java/org/grnet/cat/services/MailerService.java, service/src/main/java/org/grnet/cat/services/UserService.java, service/src/main/java/org/grnet/cat/services/ValidationService.java
email body changed to html templates, using quarkus qute template
=> CAT-330 add HTML body of email

CHANGELOG.md, api/config/quarkus-realm.json, api/src/main/resources/application.properties
We have renamed the Keycloak scopes.
=> Naming convention to Keycloak

api/src/main/resources/application.properties, api/src/main/resources/templates/user_created_validation.html, enum/src/main/java/org/grnet/cat/enums/MailType.java, service/src/main/java/org/grnet/cat/services/MailerService.java
this is a test for images inside mail
=> test mail with image

api/src/main/resources/application.properties, service/src/main/java/org/grnet/cat/services/MailerService.java
=> with param in application properties

api/src/main/resources/templates/admin_created_validation.html, api/src/main/resources/templates/user_created_validation.html, service/src/main/java/org/grnet/cat/services/MailerService.java, service/src/main/java/org/grnet/cat/services/UserService.java
send one email to administrator if user is both validated and administrator
=> CAT-339 If i am a Validated User and an Administrator i get the email twice when i make a validation request

api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, entity/src/main/java/org/grnet/cat/converter/StatusAttributeConverter.java, enum/src/main/java/org/grnet/cat/enums/ValidationStatus.java, repository/src/main/java/org/grnet/cat/repositories/UserRepository.java
1 ) added REJECTED status to search filters
2)  AND instead of OR to search users on roles and search fields. ** needed () to be added in order to be handled as an AND in the query
=> Fix minor issues in admin search tabs

service/src/main/java/org/grnet/cat/services/MailerService.java
it is a minor fix to how mail title appears
=> it is a minor fix to remove - from mail title

api/src/main/resources/application.properties, service/src/main/java/org/grnet/cat/services/MailerService.java
added in application.properties a param api.name 
this signifies the name of the instance and it will be used to build the title in the mails sent by the api
=> name the running instance to build the mail title

entity/src/main/resources/db/migration/templates/service/V1.58__update_service_template_v5.sql
added the missing question under C21 criterion for Service Provider template. Added a new script in templates
=> CAT-366 Service Provider / C21: RI Integration / Question is missing

CHANGELOG.md, api/src/test/java/org/grnet/cat/api/ValidationsEndpointTest.java, entity/src/main/resources/db/migration/tables/V1.59__db_utf8_encoding.sql
=> CAT-384 Enable Utf-8 character set in cat db

CHANGELOG.md, entity/src/main/resources/db/migration/templates/service/V1.63__update_service_template.sql
Removed duplicate test in C31 , in service provider template
=> CAT-402 Duplicate test in assessment template

CHANGELOG.md, entity/src/main/resources/db/migration/tables/json_schema/V1.67__update_json_schema_v6.sql, entity/src/main/resources/db/migration/templates/service/V1.66__update_service_template.sql
Change service provider template to add threshold_locked field and change json schema to support this change and validate correctly the template
=> CAT-419 Flag thresholds as locked when having a required default value

CHANGELOG.md, entity/src/main/resources/db/migration/templates/national_policy/V1.71__update_manager_template_national.sql
Update on manager template of national policy
=> CAT-429 Update Manager Template for National PID policy

api/pom.xml, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/SubjectsEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/TemplatesEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/UsersEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/ValidationsEndpoint.java, api/src/main/java/org/grnet/cat/api/filters/RegistrationFilter.java, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AdminJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AdminPartialJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/UserJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/UserPartialJsonAssessmentResponse.java, mapper/pom.xml, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, pom.xml, service/pom.xml, service/src/main/java/org/grnet/cat/services/SubjectService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAbstractAssessmentService.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java, service/src/main/java/org/grnet/cat/services/interceptors/ShareableEntityInterceptor.java, util/pom.xml, util/src/main/java/org/grnet/cat/utils/Utility.java
This attribute indicates that the assessment has been shared with a user.
=> Add a new json assessment response attribute

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, api/src/test/java/org/grnet/cat/api/AdminEndpointTest.java, api/src/test/java/org/grnet/cat/api/KeycloakTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/PrincipleRequestDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/PrincipleResponseDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/PrincipleUpdateDto.java, entity/src/main/java/org/grnet/cat/entities/Principle.java, entity/src/main/resources/db/migration/tables/principles/V1.74__principles.sql, exception/src/main/java/org/grnet/cat/exceptions/UniqueConstraintViolationException.java, mapper/src/main/java/org/grnet/cat/mappers/PrincipleMapper.java, repository/src/main/java/org/grnet/cat/repositories/PrincipleRepository.java, service/src/main/java/org/grnet/cat/services/PrincipleService.java, validator/src/main/java/org/grnet/cat/constraints/ValidUuid.java
=> CAT-443 CRUD actions on Principles

CHANGELOG.md, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AdminJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AdminPartialJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/UserJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/UserPartialJsonAssessmentResponse.java, entity/src/main/java/org/grnet/cat/entities/Assessment.java, entity/src/main/resources/db/migration/tables/assessment/V1.83__add_column.sql, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, repository/src/main/java/org/grnet/cat/repositories/AssessmentRepository.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
we wll need to change the V1.83__add_column.sql script to V1.84__add_column.sql , after the 252 PR is closed as there will be a conflict in flyway
a boolean "shared" field is added to the Assessment table
a boolean "shared" field is added to the Assessment responses that an Admin user receives, and defines if the Assessment is shared or not
a boolean "shared_by_user" is added to the Assessment responses that a Validated user receives , that defines if the Assessment is shared by him to other users
* we already have a boolean "shared_to_user" that defines if the Assessement is shared to the Valdated user, by another user
=> CAT-459 As a user i want to see to whom i shared an assessment

api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/CommentResponseDto.java, entity/src/main/java/org/grnet/cat/entities/Comment.java, entity/src/main/resources/db/migration/tables/assessment_comments/V1.84__add_modified_on.sql, service/src/main/java/org/grnet/cat/services/CommentService.java
CAT-465: Add more user info on each comment
=> CAT-465: Add more user info on each comment

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/RegistryCodelistEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/RegistryCodelistEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/codelist/TypeCriterionResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Registry.java, entity/src/main/java/org/grnet/cat/entities/registry/TypeCriterion.java, entity/src/main/resources/db/migration/tables/registry/V1.86__t_type_criterion.sql, mapper/src/main/java/org/grnet/cat/mappers/registry/TypeCriterionMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/TypeCriterionRepository.java, service/src/main/java/org/grnet/cat/services/ActorService.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java, service/src/main/java/org/grnet/cat/services/registry/TypeCriterionService.java, validator/src/main/java/org/grnet/cat/constraints/ValidUrl.java, validator/src/main/java/org/grnet/cat/validators/UrlValidator.java
this is a crud for type criterion
=> CAT-484 Codelist - Tables sync with Vocabulary service  (CRUD Type Criterion)

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/RegistryCodelistEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/RegistryCodelistEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/codelist/ImperativeResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Imperative.java, entity/src/main/resources/db/migration/tables/registry/V1.87__s_imperative.sql, mapper/src/main/java/org/grnet/cat/mappers/registry/ImperativeMapper.java, mapper/src/main/java/org/grnet/cat/mappers/registry/TypeCriterionMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/ImperativeRepository.java, service/src/main/java/org/grnet/cat/services/registry/ImperativeService.java, service/src/main/java/org/grnet/cat/services/registry/TypeCriterionService.java
GET /codelist/imperative
GET /codelist/imperative/{id}
=> CAT-484 Codelist - Tables sync with Vocabulary service (GET Imperative)

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/RegistryCodelistEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/RegistryCodelistEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/codelist/TypeBenchmarkResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/TypeBenchmark.java, entity/src/main/resources/db/migration/tables/registry/V1.89__t_type_benchmark.sql, mapper/src/main/java/org/grnet/cat/mappers/registry/TypeBenchmarkMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/TypeBenchmarkRepository.java, service/src/main/java/org/grnet/cat/services/registry/TypeBenchmarkService.java
GET /codelist/type-benchmark
GET /codelist/type-benchmark/{id}
=> CAT-484 Codelist - Tables sync with Vocabulary service (GET Benchmark Type).

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/RegistryCodelistEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/MotivationEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/InformativeResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/MotivationActorPartialResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/MotivationActorRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/MotivationActorResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/RelationResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/codelist/RegistryActorResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/motivation/MotivationResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Motivation.java, entity/src/main/java/org/grnet/cat/entities/registry/MotivationActorId.java, entity/src/main/java/org/grnet/cat/entities/registry/MotivationActorJunction.java, entity/src/main/java/org/grnet/cat/entities/registry/MotivationPrincipleId.java, entity/src/main/java/org/grnet/cat/entities/registry/Registry.java, entity/src/main/java/org/grnet/cat/entities/registry/RegistryActor.java, entity/src/main/resources/db/migration/tables/registry/V1.102__t_motivation_actor.sql, mapper/src/main/java/org/grnet/cat/mappers/registry/MotivationActorMapper.java, mapper/src/main/java/org/grnet/cat/mappers/registry/MotivationMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/RelationRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
t_Motivation_Actor table created as well as api calls to add actors and get actors for a motivation
=> CAT-476 Motivations and actors (motivation-actor relation)

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/RegistryCodelistEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/RegistryCodelistEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/RelationResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Relation.java, mapper/src/main/java/org/grnet/cat/mappers/registry/RelationMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/RelationRepository.java, service/src/main/java/org/grnet/cat/services/registry/RelationService.java
GET /relations/{id}
GET /relations
=> CAT-500 API: Get list of relations (codelist)

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/RegistryCodelistEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/MotivationEndpointTest.java, api/src/test/java/org/grnet/cat/api/registry/RegistryCodelistEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/criterion/CriterionActorRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/criterion/CriterionActorResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Criterion.java, entity/src/main/java/org/grnet/cat/entities/registry/CriterionActorId.java, entity/src/main/java/org/grnet/cat/entities/registry/CriterionActorJunction.java, entity/src/main/java/org/grnet/cat/entities/registry/RegistryActor.java, entity/src/main/resources/db/migration/tables/registry/V1.109__p_criterion_actor.sql, entity/src/main/resources/db/migration/tables/registry/V1.110__t_motivation_actor_v1.sql, mapper/src/main/java/org/grnet/cat/mappers/registry/CriterionActorMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionActorRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java, service/src/main/java/org/grnet/cat/services/registry/RegistryActorService.java
POST /motivations/{id}/actors/{actor-id}/criteria
GET /motivations/{id}/actors/{actor-id}/criteria
=> CAT-479 Criteria & actors

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/ImperativeRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MetricTestRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationTypeRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/PrincipleRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/RegistryActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/TestDefinitionRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/TestMethodRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/TestRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/TypeBenchmarkRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/TypeCriterionRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/metric/MetricRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/metric/TypeAlgorithmRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/metric/TypeMetricRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/metric/TypeReproducibilityRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
add sorting on id besides lastTouch to avoid issues during sorting same lastTouch values
=> CAT-509 Weird Principles local pagination issue when page size=5

repository/src/main/java/org/grnet/cat/repositories/registry/MotivationRepository.java
Filters on motivations on fields 
Motivation mtv, label
Actor actorLabel
=> CAT-508 Filters on Motivation

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/criterion/CriterionActorResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/criterion/PrincipleCriterionResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/principle/PrinciplePartialResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Criterion.java, entity/src/main/java/org/grnet/cat/entities/registry/RegistryActor.java, mapper/src/main/java/org/grnet/cat/mappers/registry/CriteriaMapper.java, mapper/src/main/java/org/grnet/cat/mappers/registry/PrincipleCriterionMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationRepository.java, service/src/main/java/org/grnet/cat/services/registry/CriterionService.java
GET /motivations/{id}/criteria
=> CAT-512 CAT-515  GET list of Criteria by Motivation ,Pagination issue in Motivations

CHANGELOG.md, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionRepository.java
fixed problem with size of returned results list
=> CAT-518 Pagination issues in Motivation > Actor > Criteria

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, entity/src/main/java/org/grnet/cat/entities/registry/RegistryActor.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionRepository.java, service/src/main/java/org/grnet/cat/services/registry/RegistryActorService.java
PUT /motivations/{id}/actors/{actor-id}/criteria
provide a body with all the criteria the motivation actor should have. it will remove any existing criteria not included in the request, add any criteria included in the request that does not exist in the existing actor-criteria relationship and keeps untouched the criteria included in the request and also included in the existing actor-criteria relationship
=> CAT-519 API provide a call to update the criteria of a motivation actor (assessment type)

entity/src/main/resources/db/migration/tables/registry/V1.127__update_test_definition_new_motivation.sql
update motivation-update test questions
=> update motivation-update test definition

CHANGELOG.md, repository/src/main/java/org/grnet/cat/repositories/registry/PrincipleRepository.java
fix count result in GET motivation principles
=> CAT-576 API: Pagination issue in Motivation Principles call

CHANGELOG.md, mapper/src/main/java/org/grnet/cat/mappers/registry/PrincipleCriterionMapper.java, pom.xml, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionRepository.java, service/src/main/java/org/grnet/cat/services/registry/CriterionService.java
- [#320](https://github.com/FC4E-CAT/fc4e-cat-api/pull/320) CAT-579 Remove criteria ordering logic based on unique names.
=> Version 1.8.1

CHANGELOG.md, mapper/src/main/java/org/grnet/cat/mappers/registry/CriterionActorMapper.java
duplicate principles on motivation/actor/criteria selection
=> CAT-586 Principles are displayed multiple times in motivation/actor/criteria selection

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/motivation/MotivationResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Motivation.java, entity/src/main/resources/db/migration/tables/registry/V1.141__add_published_to_motivation.sql, mapper/src/main/java/org/grnet/cat/mappers/registry/MotivationMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
add publish column in t_Motivation
implement PUT /registry/motivations/{id}/publish
add status as parameter to GET /registry/motivations to filter motivations by publish status
=> CAT-599 Add published as status in a Motivation

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/TemplatesEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java, validator/src/main/java/org/grnet/cat/constraints/CheckPublished.java, validator/src/main/java/org/grnet/cat/validators/CheckPublishedValidator.java
Change /registry/motivations POST, PUT, DELETE requests to not permit access if Motivation is published
Change /templates/by-motivation/{motivation-id}/by-actor/{actor-id} to not permit access if Motivation is unpublished
=> CAT-600 Permit actions depending on Motivation publish status

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java, validator/src/main/java/org/grnet/cat/validators/CheckPublishedValidator.java
PUT /registry/motivations/{id}/unpublish
=> CAT-603 Unpublish a published motivation

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/actor/MotivationActorResponse.java, entity/src/main/java/org/grnet/cat/entities/registry/Motivation.java, entity/src/main/java/org/grnet/cat/entities/registry/MotivationActorJunction.java, entity/src/main/resources/db/migration/tables/registry/V1.145__publish_in_motivation_actor.sql, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationActorRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
PUT /registry/motivations/{id}/actors/{actor-id}/publish
PUT /registry/motivations/{id}/actors/{actor-id}/unpublish
=> CAT-613 Publish/Unpublish motivation actor relationship

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/TemplatesEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/CriteriaEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/MetricEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/MotivationEndpointTest.java, repository/src/main/java/org/grnet/cat/repositories/ValidationRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/CriterionMetricRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MetricTestRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/MotivationActorRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/PrincipleCriterionRepository.java, service/src/main/java/org/grnet/cat/services/TemplateService.java, service/src/main/java/org/grnet/cat/services/registry/CriterionService.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java, service/src/main/java/org/grnet/cat/services/registry/PrincipleService.java, service/src/main/java/org/grnet/cat/services/registry/RegistryActorService.java, service/src/main/java/org/grnet/cat/services/registry/TestDefinitionService.java, service/src/main/java/org/grnet/cat/services/registry/TestMethodService.java, service/src/main/java/org/grnet/cat/services/registry/TestService.java, service/src/main/java/org/grnet/cat/services/registry/metric/MetricService.java, validator/src/main/java/org/grnet/cat/validators/CheckPublishedValidator.java
On UPDATE/DELETE actions on elements of a motivation permit or not , depending on the status of the motivation.
if motivation is published then we should not update/delete.
=> CAT-619 Permit actions on published/unpublished relation motivation-actor

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsV2Endpoint.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
v2/assessments/public/{id} to show a public assessment
=> CAT-627 public assessments

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsV2Endpoint.java, repository/src/main/java/org/grnet/cat/repositories/MotivationAssessmentRepository.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
/v2/registry/assessment/objects to get the list of objects in assessments
=> CAT-635 Subject (objects) filters for non-public assessments

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/TestEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/TestEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/test/CheckUrlRequestDto.java, service/src/main/java/org/grnet/cat/services/registry/TestService.java
change https check request as :  POST /v1/registry/tests/check-automated-test/https-url  accepting a json body as
{  url="https://myurl.com" }
=> CAT-638 Change call GET /v1/registry/tests/check-automated-test/https-url definition

CHANGELOG.md, api/config/quarkus-realm.json, api/src/main/java/org/grnet/cat/api/endpoints/AutomatedCheckEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/TestEndpoint.java, api/src/test/java/org/grnet/cat/api/AutomatedCheckEndpointTest.java, api/src/test/java/org/grnet/cat/api/registry/TestEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AutomatedCheckRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AutomatedCheckResponse.java, service/src/main/java/org/grnet/cat/services/AutomatedCheckService.java, service/src/main/java/org/grnet/cat/services/registry/TestService.java
This pr remains wip as it fails to forbid identified user from accessing the /v1/automated/check-url endpoint.
=> CAT-645 Create AutomatedCheck resource

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, api/src/test/java/org/grnet/cat/api/registry/MotivationEndpointTest.java
=> CAT-662 Missing junit tests for publish/unpublish motivation/motivation-actor to be added

CHANGELOG.md, entity/src/main/resources/db/migration/tables/registry/V1.46__delete_priniciple_criterion_from_eosc_pid_policy.sql
Delete secondary principle-criterion relations from EOSC PID POLICY
=> CAT-679 Script to delete secondary principles from EOSC PID POLICY motivation

CHANGELOG.md, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
When publish / unpublish motivation the motivation-actor publish status will not change
=> CAT-687 Publish/Unpublish motivation not to change motivation-actor publish status

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/CriNodeDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/MetricTestResponseDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/metric/DetailedMetricDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/motivation/MetricTestRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/template/MetricTestNode.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/registry/template/TemplateTestNode.java, entity/src/main/java/org/grnet/cat/entities/registry/MetricTestProjection.java, entity/src/main/java/org/grnet/cat/entities/registry/metric/Metric.java, mapper/src/main/java/org/grnet/cat/mappers/registry/MetricTestMapper.java, repository/src/main/java/org/grnet/cat/repositories/registry/MetricTestRepository.java, repository/src/main/java/org/grnet/cat/repositories/registry/TestDefinitionRepository.java, service/src/main/java/org/grnet/cat/services/registry/MotivationService.java
Changes: 
1) change GET /motivations/{id}/metric-test  to  GET /motivations/{id}/metrics/{id}/tests
2)  change PUT /motivations/{id}/metric-test  to PUT /motivations/{id}/metrics/{id}/tests
3) change POST /motivations/{id}/metric-test  to POST /motivations/{id}/metrics/{id}/tests
and changes to the corresponding requests and responsies
=> CAT-698 Support test-metric relations of a specific metric in a motivation

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AutomatedCheckEndpoint.java, api/src/test/java/org/grnet/cat/api/AutomatedCheckEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/ArccValidationRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/ArccValidationResponse.java, service/src/main/java/org/grnet/cat/services/ArccValidationService.java, validator/src/main/java/org/grnet/cat/validators/XmlMetadataValidator/GeneralMetadataValidator.java, validator/src/main/java/org/grnet/cat/validators/XmlMetadataValidator/MetadataValidationFactory.java, validator/src/main/java/org/grnet/cat/validators/XmlMetadataValidator/MetadataValidator.java, validator/src/main/java/org/grnet/cat/validators/XmlMetadataValidator/XmlSchemaValidator.java
**Request:**
> {
>     "test_id": "pid_graph:333489E8",
>     "metadata_url": "https://meta.sram.surf.nl/metadata/proxy_sp.xml"
> }
**Response:**
> {
>     "is_schema_compliant": true,
>     "is_test_compliant": true,
>     "feedback": "MD-1a validation passed.",
>     "test_name": "MD-1a",
>     "test_label": "Administrative Contact Details"
> }
=> CAT-650: Automated Tests for ARCC-G071

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AutomatedCheckEndpoint.java, api/src/test/java/org/grnet/cat/api/AutomatedCheckEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/ArccValidationRequest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/ArccValidationResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AutomatedCheckResponse.java, entity/src/main/resources/db/migration/tables/registry/V1.48__arcc_test_to_G071.sql, enum/src/main/java/org/grnet/cat/enums/ArccTestType.java, service/src/main/java/org/grnet/cat/services/ArccValidationService.java, validator/src/main/java/org/grnet/cat/validators/XmlMetadataValidator/MetadataValidationFactory.java, validator/src/main/java/org/grnet/cat/validators/XmlMetadataValidator/XmlSchemaValidator.java
Change Arcc Automated Check mechanism
=> CAT-618 Change metadata xml validation automated checks

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AutomatedCheckEndpoint.java, api/src/test/java/org/grnet/cat/api/AutomatedCheckEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/ArccValidationResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/AutomatedCheckResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/TestExtraInfoNodeDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/TestNodeDto.java, service/src/main/java/org/grnet/cat/services/ArccValidationService.java, service/src/main/java/org/grnet/cat/services/AutomatedCheckService.java, validator/src/main/java/org/grnet/cat/validators/XmlMetadataValidator/XmlSchemaValidator.java
extra info in responses of automated tests
=> CAT-641 Should we keep extra info on automated tests?

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AdminEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsV2Endpoint.java, api/src/test/java/org/grnet/cat/api/AssessmentsEndpointTest.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AdminPartialJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/AssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/UserPartialJsonAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/AdminJsonRegistryAssessmentResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/RegistryAssessmentDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/UserJsonRegistryAssessmentResponse.java, entity/src/main/java/org/grnet/cat/entities/MotivationAssessment.java, entity/src/main/resources/db/migration/tables/registry/V1.49__add_publish_column_in_assessment.sql, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, repository/src/main/java/org/grnet/cat/repositories/MotivationAssessmentRepository.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
Added endpoints: 
==AssessmentsV2Endpoint 
- v2/assessmets//{id}/publish
- v2/assessmets//{id}/unpublish
==AdminEndpoint
- v1/admin/assessments/{id}/unpublish
- v1/admin/assessments/{id}/unpublish
publshed field in assessment_doc is removed and is added as column in MotivationAssessment table
=> CAT-727 Publish assessment

CHANGELOG.md, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/RegistryAssessmentDto.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
Changed assessment . published would be also part of assessment_doc. 
during creation or update assessment the user will be able to define if the assessment will be public or private
=> CAT-734 Change assessment_doc to include published

entity/src/main/resources/db/migration/tables/registry/V1.51__update_Arcc_tests_v2.sql
update question text in arcc tests
=> arcc update

CHANGELOG.md, entity/src/main/java/org/grnet/cat/entities/registry/RegistryTemplate.java, entity/src/main/resources/db/migration/tables/registry/V1.53__update_registry_template_v2.sql, repository/src/main/java/org/grnet/cat/repositories/registry/RegistryTemplateRepository.java
Add criterion_actor motivation_id to filter on criteria of actor for specific motivation , when retrieving the registry_template
=> CAT-744 Issue when actor- criteria vary betwen 2 motivations which are parent-child(cloned)

codemeta.json
This PR adds a codemeta.json file to provide structured metadata for the project following the [CodeMeta 3.0](https://w3id.org/codemeta/3.0) standard.
=> Add codemeta.json for software metadata

CHANGELOG.md, codemeta.json, entity/src/main/resources/db/migration/tables/registry/V1.56__update_validation_actor.sql, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
This pr adds a script to update the validations to PID Service Provider(Role) in the cases the actor is PID Service(Component)
Also changes admin update assessments to be able to change the actor from the assessment doc . this wll be only for this pr , we we return the implementation to the previous one
=> CAT-766 Update validation actors to PID Service Provider

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/TemplatesEndpoint.java, api/src/main/java/org/grnet/cat/api/endpoints/registry/MotivationEndpoint.java, api/src/test/java/org/grnet/cat/api/ValidationsEndpointTest.java, codemeta.json, entity/src/main/resources/db/migration/tables/registry/V1.57__delete_actor.sql, util/src/main/java/org/grnet/cat/utils/Utility.java
first merge https://github.com/FC4E-CAT/fc4e-cat-api/pull/435
This pr deletes the PID Service(Component) from db and the cat service
=> CAT-767 Delete the PID Service(Component) from CAT

CHANGELOG.md, mapper/src/main/java/org/grnet/cat/mappers/registry/TestDefinitionMapper.java, service/src/main/java/org/grnet/cat/services/TemplateService.java, util/src/main/java/org/grnet/cat/utils/TestParamsTransformer.java
Applied specific replacements only for existing test parameters from the database inserts. 
New user inputs remain unchanged to preserve their original format.
=> CAT-810: Test Update Not Working Properly

CHANGELOG.md, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/registry/MetricNodeDto.java, service/src/main/java/org/grnet/cat/services/assessment/JsonAssessmentService.java
Reverts FC4E-CAT/fc4e-cat-api#456
=> Revert "CAT-825 Missing label_algorithm , label_type_metric from assessment doc"

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsV2Endpoint.java, api/src/main/resources/templates/zenodo_draft_deposit_notification.html, api/src/main/resources/templates/zenodo_publish_deposit_draft_in_db_notification.html, enum/src/main/java/org/grnet/cat/enums/MailType.java, mapper/src/main/java/org/grnet/cat/mappers/AssessmentMapper.java, repository/src/main/java/org/grnet/cat/repositories/UserRepository.java, service/src/main/java/org/grnet/cat/services/MailerService.java, service/src/main/java/org/grnet/cat/services/zenodo/ZenodoClient.java, service/src/main/java/org/grnet/cat/services/zenodo/ZenodoService.java
add endpoint to publish deposit in zenodo
=> CAT-834 Publish deposit to Zenodo

CHANGELOG.md, api/src/main/java/org/grnet/cat/api/endpoints/AssessmentsV2Endpoint.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/zenodo/ZenodoAssessmentInfoResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/zenodo/ZenodoCreatorDto.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/zenodo/ZenodoDepositResponse.java, data-transfer-object/src/main/java/org/grnet/cat/dtos/assessment/zenodo/ZenodoFileInfoDto.java, mapper/src/main/java/org/grnet/cat/mappers/ZenodoAssessmentInfoMapper.java, service/src/main/java/org/grnet/cat/services/MailerService.java, service/src/main/java/org/grnet/cat/services/zenodo/ZenodoService.java
Add endpoint  that will get deposiit info from zenodo
=> CAT-836 Get deposit info from Zenodo
